version: "3.8"
services:
  database:
    image: mariadb
    ports:
      - "3307:3306"
    volumes:
      - ./db/seeds/dev:/docker-entrypoint-initdb.d/
    environment:
      - "MYSQL_DATABASE=musicstore"
      - "MYSQL_USER=benutzer"
      - "MYSQL_PASSWORD=asdf"
      - "MYSQL_ROOT_PASSWORD=superstrongproductionpasswordtheappdoesnotknow"