spring:
  datasource:
    url: jdbc:mysql://localhost:3307/musicstore
    username: benutzer
    password: asdf
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    banner-mode: off

logging:
  level:
    root: INFO